import Image from "next/image";
import { Star, ArrowUpRight } from "lucide-react";
import { useTranslations } from "next-intl";
import { RevealOnScroll } from "@/components/RevealOnScroll";
import { ApartmentsCarousel } from "./ApartmentsCarousel";

// Reusable across the home page (embedded after Services, matching the live
// WordPress nav order) and the standalone /apartments/ route. Heading level
// swaps via prop, same contract as the other sections.
//
// Rebuilt 2026-06-11: scrapped the Airbnb embed widget approach because
// (a) 10 cross-origin iframes loaded slowly, (b) we couldn't restyle the
// embed cards (forced white background), and (c) the SDK's one-shot DOM
// scan was racing React hydration. Now each card is a fully styled link
// using the listing's og:image (fetched once via
// scripts/fetch-airbnb-og-images.mjs, baked in here). Rating is static
// from the Stage 0 inventory pass — accept that it may drift slightly
// from Airbnb's live number; re-run the fetcher if needed.
//
// Content sourced from docs/inventory/text/apartments.md.
// 10 listings: 9 in Bansko, 1 in Burgas. Two listings from the original
// inventory (Razlog id 1576107287888378227 and Bansko id 1615387914155787876)
// are excluded because their Airbnb pages are no longer available.
//
// Listing labels are the host's own Airbnb headlines (user-generated by
// the host, not Home2Host marketing copy) — kept as-is per locale. The
// city code resolves through `Apartments.cities` so EN visitors see
// "Bansko"/"Burgas" while BG visitors see "Банско"/"Бургас".

type ApartmentsSectionProps = {
  headingLevel?: "h1" | "h2";
};

type CityCode = "bansko" | "burgas";

type Listing = {
  id: string;
  // The host's headline as set on Airbnb (e.g. "Мястото на Джино 1 спалня
  // | 3 минути до Gondola"), sourced from the listing's JSON-LD `name`
  // field via scripts/fetch-airbnb-og-images.mjs and with the redundant
  // "| Home2Host" suffix stripped (our site IS Home2Host).
  label: string;
  city: CityCode;
  url: string;
  imageUrl: string;
  // `null` for ★New listings that don't have a numeric rating yet.
  rating: number | null;
};

const listings: Listing[] = [
  {
    id: "1318738434906867843",
    label: "Модерен двуетажен апартамент с 2 спални | Гледка",
    city: "bansko",
    url: "https://www.airbnb.com/rooms/1318738434906867843",
    imageUrl:
      "https://a0.muscache.com/im/pictures/hosting/Hosting-1318738434906867843/original/1fd5da3e-8516-4e5f-92b9-196d6fb80715.jpeg?im_w=720",
    rating: 4.85,
  },
  {
    id: "671609314902059816",
    label: "Апартаментът на Еди в центъра",
    city: "burgas",
    url: "https://www.airbnb.com/rooms/671609314902059816",
    imageUrl:
      "https://a0.muscache.com/im/pictures/hosting/Hosting-671609314902059816/original/25b75729-8079-4880-9660-c833c7f363a6.jpeg?im_w=720",
    rating: 4.96,
  },
  {
    id: "1571758069076515492",
    label: "Ски-вход/изход 1 спалня | Страхотна гледка | Паркинг",
    city: "bansko",
    url: "https://www.airbnb.com/rooms/1571758069076515492",
    imageUrl:
      "https://a0.muscache.com/im/pictures/hosting/Hosting-1571758069076515492/original/36135164-0845-4de8-94b4-7f02c4023161.jpeg?im_w=720",
    rating: null,
  },
  {
    id: "1607996732020225042",
    label: "Мястото на Джино 1 спалня | 3 минути до Gondola",
    city: "bansko",
    url: "https://www.airbnb.com/rooms/1607996732020225042",
    imageUrl:
      "https://a0.muscache.com/im/pictures/hosting/Hosting-1607996732020225042/original/958bc3be-d464-44d2-ba05-3f1b3d816a3a.jpeg?im_w=720",
    rating: null,
  },
  {
    id: "1607988986183197333",
    label: "Мястото на Джино 2 1 спалня | 3 минути до Gondola",
    city: "bansko",
    url: "https://www.airbnb.com/rooms/1607988986183197333",
    imageUrl:
      "https://a0.muscache.com/im/pictures/hosting/Hosting-1607988986183197333/original/4b03a4fa-d397-4ec1-8584-20caa05652cf.jpeg?im_w=720",
    rating: null,
  },
  {
    id: "1582571602551689852",
    label: "Панорамно студио | Изглед към гората | Паркинг",
    city: "bansko",
    url: "https://www.airbnb.com/rooms/1582571602551689852",
    imageUrl:
      "https://a0.muscache.com/im/pictures/hosting/Hosting-1582571602551689852/original/887cf149-729e-4bda-bcb8-01bbeef60cca.jpeg?im_w=720",
    rating: null,
  },
  {
    id: "1536078655698153217",
    label: "Алпийски апартамент с 1 спалня близо до кабинков лифт | Паркинг",
    city: "bansko",
    url: "https://www.airbnb.com/rooms/1536078655698153217",
    imageUrl:
      "https://a0.muscache.com/im/pictures/hosting/Hosting-1536078655698153217/original/01ecd934-85ea-4e38-9bd2-110cbea946d2.jpeg?im_w=720",
    rating: 4.75,
  },
  {
    id: "1544251596416809511",
    label: "Снежна 1BR Удивителна гледка | Безплатен паркинг",
    city: "bansko",
    url: "https://www.airbnb.com/rooms/1544251596416809511",
    imageUrl:
      "https://a0.muscache.com/im/pictures/hosting/Hosting-1544251596416809511/original/a3af282f-fdfc-4b6f-9d80-be217eb1b0ec.jpeg?im_w=720",
    rating: 5.0,
  },
  {
    id: "1550747815707309469",
    label: "Ски 1BR близо до гондола | Безплатен паркинг",
    city: "bansko",
    url: "https://www.airbnb.com/rooms/1550747815707309469",
    imageUrl:
      "https://a0.muscache.com/im/pictures/hosting/Hosting-1550747815707309469/original/a0c2ddf2-9d3c-4c25-835d-f47a133b77b0.jpeg?im_w=720",
    rating: 5.0,
  },
  {
    id: "1614457751120708395",
    label: "Royal Park 1BR | Страхотна гледка | Паркинг",
    city: "bansko",
    url: "https://www.airbnb.com/rooms/1614457751120708395",
    imageUrl:
      "https://a0.muscache.com/im/pictures/hosting/Hosting-1614457751120708395/original/d057b9ba-5329-4477-b3c0-84555e1db6a1.jpeg?im_w=720",
    rating: null,
  },
];

export function ApartmentsSection({
  headingLevel = "h2",
}: ApartmentsSectionProps) {
  const Heading = headingLevel;
  const t = useTranslations("Apartments");

  return (
    <section
      id="apartments"
      aria-labelledby="apartments-heading"
      className="bg-surface-muted"
    >
      <div className="mx-auto max-w-6xl px-gutter py-section">
        <span className="inline-flex items-center gap-2 rounded-full bg-brand-50 px-3 py-1 text-xs font-medium text-brand-800 dark:bg-brand-900 dark:text-brand-100">
          <span className="size-1.5 rounded-full bg-brand-600" />
          {t("eyebrow")}
        </span>

        <Heading
          id="apartments-heading"
          className="mt-6 max-w-3xl font-display text-4xl font-semibold tracking-tight sm:text-5xl md:text-6xl"
        >
          {t("heading")}
        </Heading>

        <p className="mt-6 max-w-prose text-lg leading-relaxed text-foreground-muted">
          {t("lead")}
        </p>

        <div className="mt-12">
          <ApartmentsCarousel>
            {listings.map((listing, index) => (
              <RevealOnScroll
                key={listing.id}
                delayIndex={index % 3}
                // Mobile dominates the viewport with one card + a peek of
                // the next; fixed widths from sm up.
                className="snap-start shrink-0 w-[85vw] sm:w-[320px] md:w-[360px]"
              >
                <a
                  href={listing.url}
                  target="_blank"
                  rel="noopener noreferrer"
                  // Card body bg is `bg-brand-800` — same indigo as
                  // primary CTA buttons. The colour itself is the click
                  // affordance, signalling "this is a button-shaped
                  // surface" before any explicit CTA text reads. Border
                  // brand-700 (one shade lighter than the bg) provides
                  // subtle definition without competing.
                  // Group so child hover effects (arrow, scale) coordinate
                  // with the parent link. `block` because <a> is inline
                  // by default and the rounded card needs block layout.
                  className="group block overflow-hidden rounded-2xl border border-brand-700 bg-brand-800 transition-all duration-300 ease-out hover:-translate-y-1 hover:border-brand-500 hover:shadow-2"
                >
                  {/* Photo with rating badge overlay */}
                  <div className="relative aspect-[4/3] overflow-hidden">
                    <Image
                      src={listing.imageUrl}
                      alt={listing.label}
                      fill
                      sizes="(max-width: 640px) 85vw, 360px"
                      className="object-cover transition-transform duration-500 ease-out group-hover:scale-105"
                    />
                    {/* Rating pill, top-right. Semi-transparent black
                        backdrop reads on any photo without redesigning
                        per-image. "New"/"Нов" label for listings without
                        a numeric rating yet (Airbnb's ★New listings). */}
                    <span className="absolute right-3 top-3 inline-flex items-center gap-1 rounded-full bg-black/70 px-2.5 py-1 text-xs font-medium text-white backdrop-blur-sm">
                      <Star
                        className="size-3 fill-current"
                        strokeWidth={0}
                        aria-hidden="true"
                      />
                      {listing.rating !== null
                        ? listing.rating.toFixed(2)
                        : t("ratingNew")}
                    </span>
                  </div>

                  {/* Card body — text colours locked to on-indigo since
                      the bg is brand-800 in both light AND dark mode (no
                      `dark:` variants needed; the foreground tokens that
                      swap by OS preference would be invisible in one
                      mode). Same approach as the FAQ section. */}
                  <div className="flex flex-col gap-1 p-5">
                    <div className="flex items-start justify-between gap-3">
                      <h3 className="line-clamp-2 font-display text-base font-semibold tracking-tight text-white">
                        {listing.label}
                      </h3>
                      <span
                        aria-hidden="true"
                        className="mt-0.5 inline-flex shrink-0 text-brand-200 transition-colors group-hover:text-white"
                      >
                        <ArrowUpRight className="size-5" strokeWidth={2} />
                      </span>
                    </div>
                    <span className="text-xs font-medium uppercase tracking-wider text-brand-200">
                      {t(`cities.${listing.city}`)}
                    </span>
                  </div>
                </a>
              </RevealOnScroll>
            ))}
          </ApartmentsCarousel>
        </div>
      </div>
    </section>
  );
}
