/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    'blog-posts': BlogPost;
    apartments: Apartment;
    faqs: Faq;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'blog-posts': BlogPostsSelect<false> | BlogPostsSelect<true>;
    apartments: ApartmentsSelect<false> | ApartmentsSelect<true>;
    faqs: FaqsSelect<false> | FaqsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('bg' | 'en') | ('bg' | 'en')[];
  globals: {
    'landing-page': LandingPage;
    about: About;
    services: Service;
    'pricing-plans': PricingPlan;
    contacts: Contact;
    'social-links': SocialLink;
  };
  globalsSelect: {
    'landing-page': LandingPageSelect<false> | LandingPageSelect<true>;
    about: AboutSelect<false> | AboutSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    'pricing-plans': PricingPlansSelect<false> | PricingPlansSelect<true>;
    contacts: ContactsSelect<false> | ContactsSelect<true>;
    'social-links': SocialLinksSelect<false> | SocialLinksSelect<true>;
  };
  locale: 'bg' | 'en';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-posts".
 */
export interface BlogPost {
  id: number;
  title: string;
  /**
   * URL-safe identifier, shared across locales (e.g. 'welcome-to-bansko').
   */
  slug: string;
  excerpt?: string | null;
  featuredImage?: (number | null) | Media;
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  author?: string | null;
  tags?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  publishedAt: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Airbnb listings shown on the Apartments carousel. Paste the Airbnb URL and use 'Fetch from Airbnb' to auto-fill the title and cover photo, or fill them manually.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "apartments".
 */
export interface Apartment {
  id: number;
  /**
   * Public Airbnb listing URL — any locale form works (https://www.airbnb.com/rooms/..., https://bg.airbnb.com/rooms/..., https://www.airbnb.co.uk/rooms/..., etc.). The card on the site links to whichever form you paste.
   */
  airbnbUrl: string;
  title: string;
  /**
   * Cover photo shown on the card. Auto-uploaded when you use 'Fetch from Airbnb', or upload manually.
   */
  featuredImage: number | Media;
  /**
   * Star rating shown on the card (e.g. 4.85). Auto-filled by 'Fetch from Airbnb'; click the refresh icon below to pull just the latest number from Airbnb without overwriting title or photo. Leave empty to hide the rating pill (use for ★New listings).
   */
  rating?: number | null;
  city: 'bansko' | 'burgas' | 'razlog';
  /**
   * Lower numbers appear first.
   */
  order?: number | null;
  /**
   * Uncheck to hide from the site without deleting.
   */
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs".
 */
export interface Faq {
  id: number;
  question: string;
  answer: string;
  category?: ('owners' | 'guests' | 'general') | null;
  /**
   * Lower numbers appear first within a category.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'blog-posts';
        value: number | BlogPost;
      } | null)
    | ({
        relationTo: 'apartments';
        value: number | Apartment;
      } | null)
    | ({
        relationTo: 'faqs';
        value: number | Faq;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-posts_select".
 */
export interface BlogPostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  featuredImage?: T;
  body?: T;
  author?: T;
  tags?:
    | T
    | {
        label?: T;
        id?: T;
      };
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "apartments_select".
 */
export interface ApartmentsSelect<T extends boolean = true> {
  airbnbUrl?: T;
  title?: T;
  featuredImage?: T;
  rating?: T;
  city?: T;
  order?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs_select".
 */
export interface FaqsSelect<T extends boolean = true> {
  question?: T;
  answer?: T;
  category?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Editable copy + photos for the home-page hero — the first thing visitors see. Title is split into three parts so the highlighted phrase (rendered in brand indigo) is editable as plain text. Add multiple images to enable a slow crossfade slideshow; leave the images list empty to show the built-in default photo.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "landing-page".
 */
export interface LandingPage {
  id: number;
  eyebrow: string;
  /**
   * First part of the heading, before the highlighted phrase. Leave empty if the highlight starts the title.
   */
  titleBefore?: string | null;
  /**
   * The phrase rendered in the brand indigo accent color. Leave empty to skip the highlight entirely.
   */
  titleHighlight?: string | null;
  /**
   * Trailing part of the heading, after the highlighted phrase. Often just punctuation (e.g. '.'). Leave empty if not needed.
   */
  titleAfter?: string | null;
  lead: string;
  /**
   * The main filled button (right-most prominence). Required.
   */
  primaryCta: {
    label: string;
    /**
     * Where the button goes. Use a relative path (e.g. '/contacts/') for internal links — locale prefix is added automatically for EN visitors. Use a full URL ('https://…') for external links — those open in a new tab.
     */
    url: string;
  };
  /**
   * The secondary outlined button. Required.
   */
  secondaryCta: {
    label: string;
    /**
     * Same convention as the primary button.
     */
    url: string;
  };
  /**
   * Hero photos. Leave empty to show the built-in default photo. Add one for a single static photo. Add two or more for a slow crossfade slideshow on the home page (6s per image with a 1s fade). Alt text for each photo comes from the Media doc's own Alt field.
   */
  images?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Editable copy for the 'About us' section (embedded on the home page and shown at /about-us/). Two paragraphs sit side-by-side on desktop and stack on mobile.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about".
 */
export interface About {
  id: number;
  eyebrow: string;
  heading: string;
  paragraph1: string;
  paragraph2: string;
  /**
   * Browser tab + Google result title for /about-us/.
   */
  metaTitle?: string | null;
  /**
   * Google result snippet + social-share description.
   */
  metaDescription?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Editable copy for the 'Services' section. Exactly 6 items — the layout is built for that count (6-up overview grid + 6 alternating editorial rows). Use the 'Key' select on each item to pick which icon and fallback photo show; reordering the array reorders the cards visually.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  eyebrow: string;
  heading: string;
  lead: string;
  closing: string;
  /**
   * Exactly 6 items. Don't add or remove rows — edit in place.
   */
  items?:
    | {
        /**
         * Pick the visual identity for this row. Drives the icon and the fallback photo (used if no custom Image is uploaded). Each key should appear exactly once.
         */
        key: 'profile' | 'pricing' | 'communication' | 'cleaning' | 'interior' | 'security';
        title: string;
        body: string;
        imageAlt: string;
        /**
         * Optional custom photo for this row. Leave empty to use the built-in fallback for the chosen Key.
         */
        image?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * Browser tab + Google result title for /services/.
   */
  metaTitle?: string | null;
  /**
   * Google result snippet + social-share description.
   */
  metaDescription?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Editable copy for the 'Pricing' section. Exactly 3 plans — the 3-up grid is built for that count and would wrap awkwardly with a 4th card. Use the 'Icon' select on each plan to pick which icon shows.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pricing-plans".
 */
export interface PricingPlan {
  id: number;
  eyebrow: string;
  heading: string;
  lead: string;
  /**
   * Button label on every plan card.
   */
  cta: string;
  /**
   * Exactly 3 plans. Don't add or remove cards — edit in place.
   */
  plans?:
    | {
        /**
         * Icon shown on the card header. Each icon should appear exactly once.
         */
        icon: 'rocket' | 'house' | 'wand';
        name: string;
        /**
         * Short line under the plan name (e.g. 'One-off service').
         */
        cadence: string;
        /**
         * The price as text — either a number ('200', '25') or a phrase ('Custom quote'). Phrases skip the unit treatment.
         */
        price: string;
        /**
         * Unit shown next to a numeric price (e.g. 'EUR', '%'). Leave empty for phrase-style prices.
         */
        priceUnit?: string | null;
        features?:
          | {
              label: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Browser tab + Google result title for /prices/.
   */
  metaTitle?: string | null;
  /**
   * Google result snippet + social-share description.
   */
  metaDescription?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Editable copy + contact data for the 'Contacts' section (embedded on the home page and shown at /contacts/). Also feeds the floating call button, the footer email, and the SEO structured data.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contacts".
 */
export interface Contact {
  id: number;
  eyebrow: string;
  heading: string;
  lead: string;
  /**
   * Heading on the small 'Where we work' card (e.g. 'Къде работим?').
   */
  serviceAreaHeading: string;
  /**
   * Body of the 'Where we work' card — short description of the service area.
   */
  serviceAreaBody: string;
  /**
   * Browser tab + Google result title for /contacts/.
   */
  metaTitle?: string | null;
  /**
   * Google result snippet + social-share description.
   */
  metaDescription?: string | null;
  email: string;
  /**
   * The 'main' phone. Used wherever a single number is needed (the floating call bubble, the WhatsApp button), and shown first in the phone list on the Contacts section.
   */
  primaryPhone: {
    /**
     * What visitors see (e.g. '+359 88 514 6191'). Spaces allowed.
     */
    display: string;
    /**
     * What goes into tel: and wa.me/ links. No spaces. Keep the leading + (e.g. '+359885146191').
     */
    dial: string;
  };
  /**
   * Optional second phone, shown only on the Contacts section under the primary one. Leave both fields empty if there's only one number.
   */
  secondaryPhone?: {
    /**
     * Optional — leave blank to hide the second phone.
     */
    display?: string | null;
    /**
     * Required if 'Display' is filled. No spaces, keep the leading +.
     */
    dial?: string | null;
  };
  /**
   * The displayed street address as one line (e.g. '2770 гр. Банско, ул. Кралев двор №5').
   */
  addressLine: string;
  /**
   * Google Maps link the address text points at. Open Google Maps, search the address, click Share → Copy link, paste here.
   */
  addressMapsUrl: string;
  /**
   * Optional — free-form text, one line per row.
   */
  workingHours?: string | null;
  /**
   * Optional — Google Maps embed URL (the src attribute from the embed iframe). Not currently rendered, kept for future map block.
   */
  mapEmbedUrl?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "social-links".
 */
export interface SocialLink {
  id: number;
  links?:
    | {
        platform: 'facebook' | 'instagram' | 'youtube' | 'tiktok' | 'linkedin' | 'airbnb' | 'booking';
        url: string;
        /**
         * Optional accessible label. Falls back to the platform name in the frontend.
         */
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "landing-page_select".
 */
export interface LandingPageSelect<T extends boolean = true> {
  eyebrow?: T;
  titleBefore?: T;
  titleHighlight?: T;
  titleAfter?: T;
  lead?: T;
  primaryCta?:
    | T
    | {
        label?: T;
        url?: T;
      };
  secondaryCta?:
    | T
    | {
        label?: T;
        url?: T;
      };
  images?:
    | T
    | {
        image?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about_select".
 */
export interface AboutSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  paragraph1?: T;
  paragraph2?: T;
  metaTitle?: T;
  metaDescription?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  lead?: T;
  closing?: T;
  items?:
    | T
    | {
        key?: T;
        title?: T;
        body?: T;
        imageAlt?: T;
        image?: T;
        id?: T;
      };
  metaTitle?: T;
  metaDescription?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pricing-plans_select".
 */
export interface PricingPlansSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  lead?: T;
  cta?: T;
  plans?:
    | T
    | {
        icon?: T;
        name?: T;
        cadence?: T;
        price?: T;
        priceUnit?: T;
        features?:
          | T
          | {
              label?: T;
              id?: T;
            };
        id?: T;
      };
  metaTitle?: T;
  metaDescription?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contacts_select".
 */
export interface ContactsSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  lead?: T;
  serviceAreaHeading?: T;
  serviceAreaBody?: T;
  metaTitle?: T;
  metaDescription?: T;
  email?: T;
  primaryPhone?:
    | T
    | {
        display?: T;
        dial?: T;
      };
  secondaryPhone?:
    | T
    | {
        display?: T;
        dial?: T;
      };
  addressLine?: T;
  addressMapsUrl?: T;
  workingHours?: T;
  mapEmbedUrl?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "social-links_select".
 */
export interface SocialLinksSelect<T extends boolean = true> {
  links?:
    | T
    | {
        platform?: T;
        url?: T;
        label?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}